# environment.yml
name: best_laptop_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - django=4.2
  - psycopg2
  - boto3
  - django-storages
  - python-dotenv
  - djangorestframework
  - django-cors-headers
  - pillow
  - pip